# Generated by Django 5.1.3 on 2024-12-05 02:16

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floodmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('min_lat', models.FloatField()),
                ('min_lng', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('max_lng', models.FloatField()),
                ('flood_date', models.DateTimeField()),
                ('days_before_flood', models.IntegerField()),
                ('days_after_flood', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('floodmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.floodmap')),
                ('status', models.CharField(choices=[('Progressing', 'Progressing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Progressing', max_length=50)),
                ('stage', models.CharField(choices=[('Pending approval', 'Pending approval'), ('Waiting in queue', 'Waiting in queue'), ('Downloading precipitation data', 'Downloading precipitation data'), ('Downloading Sentinel-1 images', 'Downloading Sentinel-1 images'), ('Preprocessing Sentinel-1 images', 'Preprocessing Sentinel-1 images'), ('Performing statistical analysis', 'Performing statistical analysis'), ('Classifying floodwater', 'Classifying floodwater'), ('Committing results', 'Committing results'), ('Completed', 'Completed')], default='Pending approval', max_length=200)),
                ('error_trace', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('floodmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.floodmap')),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('geoserver_workspace', models.CharField(max_length=200)),
                ('esa_world_cover_layer', models.CharField(max_length=200)),
                ('s1_backscatter_layer', models.CharField(max_length=200)),
                ('t_score_layer', models.CharField(max_length=200)),
                ('flooded_regions_layer', models.CharField(max_length=200)),
                ('thumbnail_url_params', models.CharField(max_length=500)),
                ('land_cover_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('s1_backscatter_quantiles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('t_score_quantiles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
